# Generated by Django 4.2.7 on 2023-12-25 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.URLField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
            ],
        ),
    ]
