# Generated by Django 4.2.7 on 2023-12-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
