# Generated by Django 4.2.7 on 2023-11-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(default='', max_length=160),
            preserve_default=False,
        ),
    ]
