# Generated by Django 4.2.7 on 2024-01-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xs', models.PositiveIntegerField(verbose_name='XS')),
                ('s', models.PositiveIntegerField(verbose_name='S')),
                ('m', models.PositiveIntegerField(verbose_name='M')),
                ('l', models.PositiveIntegerField(verbose_name='L')),
                ('xl', models.PositiveIntegerField(verbose_name='XL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
