# Generated by Django 4.2.7 on 2024-01-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productsizequantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsizequantity',
            options={'verbose_name_plural': 'Product size and Quantities'},
        ),
        migrations.AlterField(
            model_name='productsizequantity',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
