# Generated by Django 4.2.7 on 2024-02-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productsizequantity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsizequantity',
            options={'verbose_name_plural': 'Product size and quantities'},
        ),
        migrations.AlterField(
            model_name='productsizequantity',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size_quantity', to='product.product'),
        ),
    ]
