# Generated by Django 4.2.7 on 2023-11-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_image'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItemSerializer',
            new_name='CartItem',
        ),
    ]
